### ISSUE TITLE
_CurrencyEnumType should work with an integer numeric call

### ISSUE THREAD

**Issue by trunet** [koldakov/pycountries#11]
When using integer, it should work, instead is returning an error:

```
...
pydantic_core._pydantic_core.ValidationError: 1 validation error for Ticker
currency
  Value error, "986" is not a valid Currency [type=value_error, input_value=986, input_type=int]
    For further information visit https://errors.pydantic.dev/2.8/v/value_error
```

My schema is like this:
```
class TickerBase(BaseModel):
    ticker: str
    currency: Currency

    @field_validator("currency", mode="before")
    def parse_currency(cls, value):
        if isinstance(value, int):
            return Currency(value)
        return value
```

**Comment by koldakov** [comment]
Hi @trunet,

That's a nice catch, however, numeric is not int, it's str, cause it can start with "0", for example ``pycountries.Currency.AUD``.

Let me think if I can fit it quickly or I would appreciate if you have any suggestions.

The same for ``pycountries.Country``.

**Comment by koldakov** [comment]
I have an idea how to get values by ID, but keep in mind the numeric in CurrencyUnit still will be str, for example:

```
>>> import pycountries
>>> code = 986
>>> currency = pycountries.Currency(code)
>>> currency.numeric == code
>>> False
```

There is a PR, let me know if you are OK with these changes
https://github.com/koldakov/pycountries/pull/12

**Comment by trunet** [comment]
@koldakov yeah, this did the trick. thank you. you can go ahead and close this issue once the PR is merged.
